# Site
repository: tungpham42/tungpham42.github.io
favicon: images/favicon.ico

# Dark Mode (true/false/never)
darkmode: true

# Personal info
name: Tung Pham
title: Webmaster and Frontend Developer
email: tung.42@gmail.com
website: https://tungpham42.info

# Social links
facebook_username: tungpham42
linkedin_username: tungpham42
twitter_username: tungpham42
github_username:  tungpham42
stackoverflow_username: "3689856"
# flickr_username: jekyll
# instagram_username: chillwildlife
# dribbble_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-50HKXL041G"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/tung.jpg
about_content: | # this will include new lines to allow paragraphs
  - I have 8 years of experience in both Frontend and Backend stacks but is stronger at Frontend stack.
  - My Frontend stack is HTML5, CSS3, SASS/SCSS, Javascript, JQuery, and Bootstrap 4.
  - My Backend stack is PHP 7, Laravel 8, MySQL/MariaDB, Wordpress 5.5, and Xenforo 2.2.
  - I can also work with Git, Composer, NPM, CPanel, DirectAdmin, CentOS, Ubuntu, Slack, Trello, and Jira. 
  - I am currently open for Part-time and Remote jobs.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in administrating and developing websites, some of my other interests and hobbies are:
   - Practicing Yoga
   - Playing board games such as Xiangqi, Uno, Splendor, and Reversi.

# Footer
footer_show_references: false

# Build settings
remote_theme: tungpham42/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
